files:
  - source: /src/main/resources/io/jenkins/plugins/column/console/**/*.properties
    translation: /src/main/resources/io/jenkins/plugins/column/console/**/%file_name%_%two_letters_code%.properties
